FROM node:16-buster as builder
WORKDIR /opt/app
COPY . .

RUN npm i -g pnpm
RUN pnpm install
ENV NODE_ENV production
RUN npm run build

FROM node:14
RUN mkdir /mnt/efs

WORKDIR /opt/app
COPY --from=builder /opt/app/.next .next
COPY --from=builder /opt/app/node_modules node_modules
COPY --from=builder /opt/app/package.json package.json
COPY --from=builder /opt/app/next.config.js next.config.js
COPY --from=builder /opt/app/pnpm-lock.yaml pnpm-lock.yaml
COPY --from=builder /opt/app/public public
COPY --from=builder /opt/app/.next/static public/_next/static
EXPOSE 3000

ENV NODE_ENV production

CMD [ "npm", "start" ]